---
title: "03_modeling"
author: "Jessica Mankewitz"
date: "5/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
library(ggplot2)
library(patchwork)
library(tidyverse)
library(rcompanion)
library(PNWColors)
set.seed(1000)

read_path <- here("data/processed_data/")
write_path <- here("data/derived_data/")
fig_path <- here("figures/")
```

```{r}
attention_checks.df <- read_csv(file = paste0(read_path, "raw_attention_checks.csv"),
                                col_types = cols(aoa = col_character(), 
                                                 orig_aoa = col_character()))
raw_lemma_estimations.df <- read_csv(file = paste0(read_path, "raw_lemma_estimations.csv"),
                                col_types = cols(aoa = col_character(), 
                                                 orig_aoa = col_character()))
raw_sense_estimations.df <- read_csv(file = paste0(read_path, "raw_sense_estimations.csv"),
                                col_types = cols(aoa = col_character(), 
                                                 orig_aoa = col_character()))
raw_demographics <- read_csv(paste0(read_path, "demographics.csv"))

get_pos <- function(sense_name){
  return(gsub(".*[.]([^.]+)[.].*", "\\1", sense_name))
}
raw_sense_estimations.df$pos <- unlist(lapply(raw_sense_estimations.df$sense_name, get_pos))
```

```{r}
# Drop any participant who failed at least one attention check
failed_attention_participants <-raw_demographics %>% select(participant_id, finished) %>% left_join(attention_checks.df) %>% 
  filter(aoa != "7" | is.na(aoa)) %>% distinct(participant_id) %>% deframe()

dropped_non_eng_fl <- raw_demographics %>% filter(eng_first_lang != "Yes") %>%
  distinct(participant_id) %>% deframe()

lemma_estimations.df <- raw_lemma_estimations.df %>% 
  filter(!participant_id %in% failed_attention_participants,
         !participant_id %in% dropped_non_eng_fl)
sense_estimations.df <- raw_sense_estimations.df %>% 
  filter(!participant_id %in% failed_attention_participants,
         !participant_id %in% dropped_non_eng_fl)
demographics.df <- raw_demographics %>%
  filter(!participant_id %in% failed_attention_participants)

```




